config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



root 'posts#index', as: 'home'

get 'about' => 'pages#about', as: 'about'

resources :posts do 
	resources :comments
end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base 
	has_many :comments, dependent: :destroy
	validates :title, presence: true,
						length: {minimum: 5}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	http_basic_authenticate_with name: "Keenen", password:"1991", only: [:destroy]

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comments_params)
		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end

	private def comments_params
		params.require(:comment).permit(:username, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	    @title = 'About us';
		@content = 'Black Nuance was founded in 2019 by Keenen Mitchell, 
		an Information Technology student that had a great interest in political and social topics. 
		Here at Black Nuance, our goal is to provide a space for users to share their political and 
		social views and opinions in a protected environment. Whether you are a Republican, Democrat, 
		Libertarian, or not affiliated with any party at all, all viewpoints are welcome here. 
		We strive for an atmosphere where users can educate one another and also have discussions 
		on both subjects they agree and disagree on. We hope Black Nuance is able to positively 
		inform and share contrasting takes on political and social issues and news.';
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	http_basic_authenticate_with name: "Keenen", password:"1991", except: [:index, :show]

	def index
		 @posts = Post.all

	end

	def show
		@post = Post.find(params[:id])
	end

	def new 
		@post = Post.new
	end

	def create
		#render plain: params[:post].inspect
		@post = Post.new(post_params)

		if (@post.save)
		redirect_to @post 
	else
		render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
	@post = Post.find(params[:id])
	
if (@post.update(post_params))
		redirect_to @post 
	else
		render 'edit'

	end
end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy 

		redirect_to posts_path
	end

	private def post_params
		params.require(:post).permit(:title, :body)
	


	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
<div class="well">
<p><strong><%= comment.username %></strong>: <%= comment.body %></p>
<%= link_to 'Delete comment', [comment.post, comment],
			method: :delete,
			data: { confirm: 'Are you sure?' } %></p>
</div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
<%= f.label :username %><br>
		<%= f.text_field(:username , {:class => 'form-control'}) %> 
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>  
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Black Nuance: Political Blog</title>
  <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= csrf_meta_tags %>
  </head>

  <body>

  	<nav class="navbar navbar-default">
  		<div class="container">
  			<div class="navbar-header">
  				<button type="button" class="navbar-toggle collapsed"
  				data-toggle="collapsed" data-target="#navbar"
  				aria-expanded="false" aria-controls="navbar">
  					<span class="sr-only">Toggle navigation</span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  					<span class="icon-bar"></span>
  				</button>
  				<%= image_tag("logo/blacknuancelogo.PNG") %>
          <a class ="navbarbrand" href="#"> Black Nuance Blog</a>
  			</div>
  			<div id="navbar" class="collapse navbar-collapse">
  				<ul class="nav navbar-nav">
  					<li><%=link_to "Home", home_path %></li>
  				</ul>
  				<ul class="nav navbar-nav navbar right">
  					<li><%=link_to "Create Post", new_post_path %></li>
  				</ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%=link_to "About Us", about_path %></li>
          </ul>
  			</div>
  		</div>
  	</nav>
  <div class = "container"
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<b><h1 class="about-us-header"><%= @title %></h1></b>
<p class="aboutusdesign2"> <%= @content %> </p>
<p class="aboutuspicture"> <%= image_tag("logo/JFK.jpg") %> <%= image_tag("logo/frederickdouglass.jpg") %> 
	<%= image_tag("logo/ronpaul.jpg") %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
			<% end %>
			<% end %>
				<p>
		<%= f.label :title %><br>
		<%= f.text_field(:title , {:class => 'form-control'}) %> 
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>  
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/posts/index.html.erb
<h1 class="home-header" style="font-size:35px"><b>Blog Posts</b></h1>
<% @posts.each do |post| %>
	<div class="well">
		<h3><%= post.title %></h3>
		<p class="blogpostdesign"><%= post.body %></p>
		<%= link_to "Read More", post_path(post), :class => 'btn 
	btn-default' %>
	</div>
<% end %>

app/views/posts/new.html.erb
<h1 class="new-post-header" style="font-size: 35px"><b>Add Post</b></h1>
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
			<% end %>
			<% end %>
				<p>
		<%= f.label :title %><br>
		<%= f.text_field(:title , {:class => 'form-control'}) %> 
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>  
	</p>

	<p>
		<%= f.submit({:class => 'btn btn-primary'}) %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn 
	btn-default' %>
<%= link_to "Delete", post_path(@post),
			method: :delete,
			data: {confirm: 'Are you sure?'}, 
			:class => 'btn btn-danger' %>
<hr>



<%= render 'comments/comments' %> 
<%= render 'comments/form' %>